/**
 * Utility for applying custom token values dynamically via CSS custom properties
 */

import type { CustomTokens } from './tokenStorage';

const STYLE_ID = 'custom-tokens-style';

/**
 * Convert nested token object to flat CSS custom properties
 * Example: { color: { brand: { primary: { 500: '#ff0000' } } } }
 * becomes: { '--color-brand-primary-500': '#ff0000' }
 */
export function flattenTokens(
  obj: any,
  prefix: string = '--',
  separator: string = '-'
): Record<string, string> {
  const result: Record<string, string> = {};

  function recurse(current: any, path: string[] = []): void {
    if (current === null || current === undefined) {
      return;
    }

    if (typeof current === 'object' && !Array.isArray(current)) {
      // Check if this is a token value object (has $value property)
      if ('$value' in current) {
        const key = prefix + path.join(separator);
        result[key] = current.$value;
        return;
      }

      // Otherwise, recurse into the object
      for (const [key, value] of Object.entries(current)) {
        recurse(value, [...path, key]);
      }
    } else {
      // Direct value
      const key = prefix + path.join(separator);
      result[key] = String(current);
    }
  }

  recurse(obj);
  return result;
}

/**
 * Apply custom tokens to the document by injecting CSS custom properties
 */
export function applyCustomTokens(tokens: CustomTokens, targetElement?: HTMLElement): void {
  const flatTokens = flattenTokens(tokens);

  // Create or update style element
  let styleElement = document.getElementById(STYLE_ID) as HTMLStyleElement;

  if (!styleElement) {
    styleElement = document.createElement('style');
    styleElement.id = STYLE_ID;
    document.head.appendChild(styleElement);
  }

  // Build CSS rules
  const selector = targetElement ? `#${targetElement.id}` : ':root';
  const cssVariables = Object.entries(flatTokens)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n');

  styleElement.textContent = `
${selector} {
${cssVariables}
}
  `.trim();
}

/**
 * Remove custom token styles from the document
 */
export function removeCustomTokens(): void {
  const styleElement = document.getElementById(STYLE_ID);
  if (styleElement) {
    styleElement.remove();
  }
}

/**
 * Export tokens in various formats
 */
export class TokenExporter {
  private tokens: CustomTokens;

  constructor(tokens: CustomTokens) {
    this.tokens = tokens;
  }

  /**
   * Export as JSON
   */
  toJSON(pretty: boolean = true): string {
    return JSON.stringify(this.tokens, null, pretty ? 2 : 0);
  }

  /**
   * Export as W3C Design Token format (JSON)
   */
  toW3C(pretty: boolean = true): string {
    // Already in W3C format if using $value notation
    return this.toJSON(pretty);
  }

  /**
   * Export as JavaScript/ES6 module
   */
  toJS(): string {
    return `/**
 * Custom Design Tokens
 * Generated by Email Builder - Styleguide Builder
 */

export const tokens = ${JSON.stringify(this.tokens, null, 2)};

export default tokens;
`;
  }

  /**
   * Export as TypeScript module
   */
  toTypeScript(): string {
    const jsonString = JSON.stringify(this.tokens, null, 2);

    return `/**
 * Custom Design Tokens
 * Generated by Email Builder - Styleguide Builder
 */

export interface DesignTokens {
  [key: string]: any;
}

export const tokens: DesignTokens = ${jsonString};

export default tokens;
`;
  }

  /**
   * Export as CSS custom properties
   */
  toCSS(): string {
    const flatTokens = flattenTokens(this.tokens);
    const cssVariables = Object.entries(flatTokens)
      .map(([key, value]) => `  ${key}: ${value};`)
      .join('\n');

    return `/**
 * Custom Design Tokens
 * Generated by Email Builder - Styleguide Builder
 */

:root {
${cssVariables}
}
`;
  }

  /**
   * Export as SCSS variables
   */
  toSCSS(): string {
    const flatTokens = flattenTokens(this.tokens, '$', '-');
    const scssVariables = Object.entries(flatTokens)
      .map(([key, value]) => `${key}: ${value};`)
      .join('\n');

    return `/**
 * Custom Design Tokens
 * Generated by Email Builder - Styleguide Builder
 */

${scssVariables}
`;
  }

  /**
   * Download tokens in the specified format
   */
  download(format: 'json' | 'w3c' | 'js' | 'ts' | 'css' | 'scss'): void {
    let content: string;
    let filename: string;
    let mimeType: string;

    switch (format) {
      case 'json':
        content = this.toJSON();
        filename = 'custom-tokens.json';
        mimeType = 'application/json';
        break;
      case 'w3c':
        content = this.toW3C();
        filename = 'custom-tokens.w3c.json';
        mimeType = 'application/json';
        break;
      case 'js':
        content = this.toJS();
        filename = 'custom-tokens.js';
        mimeType = 'text/javascript';
        break;
      case 'ts':
        content = this.toTypeScript();
        filename = 'custom-tokens.ts';
        mimeType = 'text/typescript';
        break;
      case 'css':
        content = this.toCSS();
        filename = 'custom-tokens.css';
        mimeType = 'text/css';
        break;
      case 'scss':
        content = this.toSCSS();
        filename = 'custom-tokens.scss';
        mimeType = 'text/x-scss';
        break;
      default:
        throw new Error(`Unknown format: ${format}`);
    }

    // Create blob and download
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
