/**
 * Template Exporter Tests
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { TemplateExporter } from './TemplateExporter';
import type { Template } from '../types/template.types';

describe('TemplateExporter', () => {
  let exporter: TemplateExporter;

  beforeEach(() => {
    exporter = new TemplateExporter();
  });

  const createTestTemplate = (): Template => ({
    metadata: {
      id: 'template-1',
      name: 'Test Template',
      description: 'A test template',
      version: '1.0.0',
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    settings: {
      target: 'email',
      width: 600,
      backgroundColor: '#ffffff',
    },
    components: [
      {
        id: 'text-1',
        type: 'text',
        content: { text: 'Hello World' },
        children: [],
      },
    ],
  });

  describe('export', () => {
    it('should export template as HTML', () => {
      const template = createTestTemplate();

      const result = exporter.export(template, {
        format: 'html',
        minify: false,
      });

      expect(result.format).toBe('html');
      expect(result.html).toBeDefined();
      expect(result.html).toContain('<!DOCTYPE html>');
      expect(result.html).toContain('Test Template');
      expect(result.json).toBeUndefined();
    });

    it('should export template as JSON', () => {
      const template = createTestTemplate();

      const result = exporter.export(template, {
        format: 'json',
      });

      expect(result.format).toBe('json');
      expect(result.json).toBeDefined();
      expect(result.html).toBeUndefined();

      const parsed = JSON.parse(result.json!);
      expect(parsed.metadata.id).toBe('template-1');
    });

    it('should export template as both formats', () => {
      const template = createTestTemplate();

      const result = exporter.export(template, {
        format: 'both',
      });

      expect(result.format).toBe('both');
      expect(result.html).toBeDefined();
      expect(result.json).toBeDefined();
    });

    it('should include comments when requested', () => {
      const template = createTestTemplate();

      const result = exporter.export(template, {
        format: 'html',
        includeComments: true,
      });

      expect(result.html).toContain('<!-- Generated by Email Builder -->');
      expect(result.html).toContain('<!-- Template: Test Template -->');
    });

    it('should not include comments by default', () => {
      const template = createTestTemplate();

      const result = exporter.export(template, {
        format: 'html',
        includeComments: false,
      });

      expect(result.html).not.toContain('<!-- Generated by Email Builder -->');
    });

    it('should handle RTL settings', () => {
      const template = createTestTemplate();
      template.settings.rtl = true;

      const result = exporter.export(template, {
        format: 'html',
      });

      expect(result.html).toContain('dir="rtl"');
    });

    it('should handle locale settings', () => {
      const template = createTestTemplate();
      template.settings.locale = 'es';

      const result = exporter.export(template, {
        format: 'html',
      });

      expect(result.html).toContain('lang="es"');
    });

    it('should escape HTML in metadata', () => {
      const template = createTestTemplate();
      template.metadata.description = 'Test <script>alert("xss")</script>';

      const result = exporter.export(template, {
        format: 'html',
      });

      expect(result.html).not.toContain('<script>');
      expect(result.html).toContain('&lt;script&gt;');
    });
  });
});
